### ISSUE TITLE
T1.1 Learn JS, Mithril, d3.js, git and a bit of HTML & CSS 

### ISSUE THREAD

**Issue by Stef-Halmans** [GR47BD/frontend#1]
Learn JS, CSS and HTML [here](https://www.w3schools.com/).

You can find Mithril [here](https://mithril.js.org/). There is no need to learn it fully. 

Learn git concepts [here](https://dev.to/unseenwizzard/learn-git-concepts-not-commands-4gjc). I (Jort) recommend using Github desktop so you don't need to learn the commands, only the concepts.

Learn D3.js [here](https://www.tutorialspoint.com/d3js/index.htm).

**Comment by Basmeuw** [comment]
https://www.youtube.com/watch?v=YXmSJWBctw8&list=PLm2NNT6dTcBApVVTRTEl-jgcgFtkSPqac
Mithril JS youtube playlist
